### ISSUE TITLE
Missing feed content

### ISSUE THREAD

**Issue by muppeth** [zzottel/feed2red#4]
Seems like the content of the feed is not shown in the post (only the title and link to the oroginal post).
eg. https://hub.disroot.org/channel/disroot_state
Options used:
UseShare=N
UseQuote=Y
usecurrenttime=Y

Any idea?

**Comment by zzottel** [comment]
Just had a look. You have to use the actual feed address, not the address of the page that provides feed links.

In the case of the page above, the feed address for posts only would be https://hub.disroot.org/feed/disroot_state?f=&top=1. I haven't tested that yet, but if you used https://hub.disroot.org/channel/disroot_state , it won't work for sure.

**Comment by muppeth** [comment]
The site where we get the feeds is: https://state.disroot.org/atom This provides both the title(link) and the content, but somehow only the title is parsed to the channel (running also xmpp rss bot that parses title and content to xmpp room fromk that atom feed).

**Comment by zzottel** [comment]
Ah, ok.

I just looked at the feed. The problem is that feed2red.pl is trying to get the actual article contents, but those are empty at the feed. It only sets the \<summary\> tag with the the contents you'd like to see, but the \<content\> tag where the complete article should be is empty, which is why feed2red.pl doesn't find any text to post.

**Comment by zzottel** [comment]
(Sorry, Github got the tags wrong at my first attempt, comment above is now edited.)

**Comment by zzottel** [comment]
Actually, I just found out that it works if you use https://state.disroot.org/rss instead. :-)
